// <auto-generated />
namespace Get_A_Job.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class JobOffer2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobOffer2));
        
        string IMigrationMetadata.Id
        {
            get { return "202011210523102_JobOffer2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
