// <auto-generated />
namespace Get_A_Job.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class JobOffer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(JobOffer));
        
        string IMigrationMetadata.Id
        {
            get { return "202011190814512_JobOffer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
